services:
  - type: web
    plan: free
    name: SimpleForwardBot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/Snowball-0/SimpleForwardBot-Tg
    branch: main
    autoDeploy: false
    envVars:
      - key: API_ID
        sync: true
      - key: API_HASH
        sync: true
      - key: BOT_TOKEN
        sync: true
      - key: BOT_SESSION
        sync: true
      - key: DATABASE_URI
        sync: true
      - key: DATABASE_NAME
        sync: true
      - key: OWNER_ID
        sync: true
      - key: LOG_CHANNEL
        sync: true
      - key: TO_CHANNEL
        sync: true
      - key: FORCE_SUB
        sync: true